apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sample-applications
  namespace: openshift-gitops
spec:
  generators:
    - git:
        directories:
          - path: applications/*
        repoURL: 'https://github.com/jtovarro/ocp-gitops-argocd-at-scale-.git'
        revision: HEAD
  template:
    metadata:
      name: 'sample-{{path.basename}}'
    spec:
      destination:
        namespace: 'sample-{{path.basename}}'
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        path: '{{path}}'
        repoURL: 'https://github.com/jtovarro/ocp-gitops-argocd-at-scale-.git'
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Replace=true
          - CreateNamespace=true